name:                AlgST
version:             2.0.0
github:              "proglang/AlgST"
license:             MIT
author:              "Janek Spaderna"
copyright:           "2022 Janek Spaderna"
synopsis:            "Parser, Typechecker & Interpreter for Algebraic Session Types"

extra-source-files:
  - README.md

data-files:
  - examples/*

dependencies:
- base >= 4.16.4.0 && < 5
- algebraic-graphs ^>=0.6
- ansi-terminal
- array
- async
- call-stack
- containers >=0.5.9
- deepseq
- directory >= 1.3.2.0
- dlist
- filepath >= 1.4.2
- foldl
- generic-lens-lite
- hashable
- indexed-traversable
- lens-family >= 2.1.0 && < 3
- lens-family-th
- monad-validate
- mtl >= 2.2.1
- optparse-applicative
- scheduler
- semialign
- singletons-th
- stm
- template-haskell
- th-lift-instances
- these
- transformers
- unliftio-core
- unordered-containers
- with-utf8

ghc-options:
  - -j
  - -Wall
  # Orphans are used deliberately in multiple locations.
  - -Wno-orphans
  # Multiple warnings imported from the FreeST code. Unclear if fixes should be applied.
  - -Wno-name-shadowing
  # Ticking promoted constructors is mostly visual clutter.
  - -Wno-unticked-promoted-constructors
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -Wcompat

default-extensions:
  - BlockArguments
  - ImportQualifiedPost
  - LambdaCase

flags:
  benchmarker:
    description: "Build type equivalence benchmarker into AlgST"
    manual: True
    default: False

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  when:
    - condition: flag(benchmarker)
      dependencies:
        - gauge
      cpp-options:
        - -DALGST_BENCHMARKER

executables:
  algst:
    main:                Main.hs
    source-dirs:         exe
    dependencies:
      - AlgST
    build-tools:
      - alex
      - happy
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  tests:
    main: Spec.hs
    source-dirs: tests

    ghc-options:
      - -threaded
      - -rtsopts
      # Disabling idle collection and parallel collection improves productivity
      # (as reported by `+RTS -s`) significantly, this reduces test duration.
      - '"-with-rtsopts=-N -qg -I0"'

    build-tools:
      - algst
      - hspec-discover

    dependencies:
      - AlgST
      - hspec
      - hspec-core
      - hspec-discover
      - raw-strings-qq
      - reflection
      - typed-process
