name:                FreeST
version:             2.3.0
#github:              "githubuser/ContextFreeSession"
license:             BSD3
author:              "Bernardo Almeida, Andreia Mordido, Vasco T. Vasconcelos"
copyright:           "2020 authors"

#extra-source-files:
#- README.md
data-dir: StandardLib
data-files:
  - Prelude.fst
  - List.fst
  - File.fst

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
  - base >= 4.7 && < 5
  - array <= 0.5.4.0       # alex dependency
  - containers >=0.5.9
  - mtl >= 2.2.1
  - directory >= 1.3.2.0
  - filepath >= 1.4.2
  - optparse-applicative >= 0.16.1.0
  - control-bool >= 0.2.1
  - extra >= 1.7.9       # TODO, replace control-bool and its occurrences, there's no point on having both

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  exposed-modules:
    - FreeST
    - Paths_FreeST
    - Bisimulation.Grammar
    - Bisimulation.Bisimulation
    - Elaboration.ResolveDuality
    - Elaboration.Elaboration
#    - Equivalence.Equivalence
    - Equivalence.Normalisation
    - Syntax.Base
    - Syntax.Type
    - Syntax.Expression
    - Syntax.Kind
    - Syntax.Program
    - Parse.ParseUtils
    - Parse.Read
    - Parse.Unparser
    - Util.Error
    - Util.Warning
#    - Util.PrettyError
    - Util.FreestState
    - Util.CmdLine
#    - Util.PreludeLoader
    - Util.GetTOps
    - Parse.Lexer
    - Parse.Parser
    - Validation.Subkind
    - Validation.Terminated
    - Validation.Contractive
    - Validation.Rename
    - Validation.Kinding
    - Validation.Substitution
    - Validation.Typing
    - Validation.TypeChecking
    - Interpreter.Builtin
    - Interpreter.Eval
  ghc-options: -O2

executables:
  freest-bench:
    main:               Main.hs
    source-dirs:        freest-bench
    ghc-options:        -Wall -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - FreeST
      - gauge
